// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package robot.core.subsystems;
import robot.core.RobotMap;
import edu.wpi.first.wpilibj.Timer;
import robot.core.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Climber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController arm = RobotMap.climberArm;
    SpeedController clamp = RobotMap.climberClamp;
    SpeedController winch = RobotMap.climberWinch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Climb());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void armSet(double v) {
        arm.set(v);
    }
    
    public void winchSet(double v) {
        winch.set(v);
    }
    
    public void clamp() {
        // TODO: Experimental Values
        clamp.set(0.75);
        Timer.delay(2);
        clamp.set(0);
    }
    
    public void unClamp() {
        // TODO: Experimental Values
        clamp.set(-0.75);
        Timer.delay(2);
        clamp.set(0);
    }
    
    public void climb() {
        // TODO: Climbing
    }
}
