// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package robot.core.subsystems;
import robot.core.RobotMap;
import robot.core.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;
import edu.wpi.first.wpilibj.smartdashboard.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Shooter extends Subsystem {
    private final double DELAY = 3.0;
    private final double SECONDS_PER_REVOLUTION = 0.63694;
    private final double SPIN_RATE = 0.8;
    private final double STOP = 0.0;
    private final double PUSH = 1.0;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder encoder = RobotMap.shooterEncoder;
    SpeedController shooter = RobotMap.shooterController;
    PIDController pID = RobotMap.shooterPID;
    SpeedController piston = RobotMap.shooterPiston;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Shoot());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void spinUpShooter() {
        shooter.set(SPIN_RATE);
        Timer.delay(DELAY);
    }
    public void spinDownShooter() {
        shooter.set(STOP);
    }
    public void pushFrisbee() {
        piston.set(PUSH);
        Timer.delay(SECONDS_PER_REVOLUTION);
        piston.set(STOP);
    }
}
